const std = @import("std");

const source_url = "https://curl.se/ca/cacert.pem";
const out_path = "src/generated/cacert.zig";

const begin_marker = "-----BEGIN CERTIFICATE-----";
const end_marker = "-----END CERTIFICATE-----";

const Cert = struct {
    der: []const u8,
    label: []const u8,
};

fn fetchSource(allocator: std.mem.Allocator, io: std.Io) ![]u8 {
    var http_client: std.http.Client = .{ .allocator = allocator, .io = io };
    defer http_client.deinit();

    var out: std.Io.Writer.Allocating = .init(allocator);
    defer out.deinit();

    const result = try http_client.fetch(.{
        .location = .{ .url = source_url },
        .response_writer = &out.writer,
    });
    if (result.status != .ok) {
        std.debug.print("failed to fetch cacert.pem: status={d}\n", .{@intFromEnum(result.status)});
        return error.FetchFailed;
    }
    return try out.toOwnedSlice();
}

/// Extract the label comment preceding a PEM block (e.g. "GlobalSign Root CA").
/// curl's cacert.pem uses the format: a line of `=` followed by a label line.
fn extractLabel(pem: []const u8, marker_start: usize) []const u8 {
    // Walk backwards from BEGIN marker to find the label line.
    // Format in cacert.pem:
    //   <blank line>
    //   <label>
    //   =========...
    //   -----BEGIN CERTIFICATE-----
    var pos = marker_start;
    // Skip back over the "===..." line
    if (pos > 0) pos -= 1; // skip \n before BEGIN
    while (pos > 0 and pem[pos - 1] == '=') pos -= 1;
    if (pos > 0 and pem[pos - 1] == '\n') pos -= 1; // skip \n before ===
    // Now pos should be at end of label line
    const label_end = pos;
    while (pos > 0 and pem[pos - 1] != '\n') pos -= 1;
    const label = pem[pos..label_end];
    if (label.len == 0 or label[0] == '#') return "Unknown";
    return label;
}

fn parsePem(allocator: std.mem.Allocator, pem: []const u8) ![]Cert {
    const base64_decoder = std.base64.standard.decoderWithIgnore(" \t\r\n");

    var certs: std.ArrayList(Cert) = .empty;
    defer certs.deinit(allocator);

    var search_start: usize = 0;
    while (std.mem.indexOfPos(u8, pem, search_start, begin_marker)) |begin_pos| {
        const cert_start = begin_pos + begin_marker.len;
        const cert_end = std.mem.indexOfPos(u8, pem, cert_start, end_marker) orelse
            return error.MissingEndCertificateMarker;
        search_start = cert_end + end_marker.len;

        const encoded = std.mem.trim(u8, pem[cert_start..cert_end], " \t\r\n");
        const max_decoded_len = encoded.len / 4 * 3 + 4;
        const buf = try allocator.alloc(u8, max_decoded_len);
        const decoded_len = try base64_decoder.decode(buf, encoded);
        const der = buf[0..decoded_len];

        const label = extractLabel(pem, begin_pos);

        try certs.append(allocator, .{ .der = der, .label = label });
    }

    return try certs.toOwnedSlice(allocator);
}

fn render(allocator: std.mem.Allocator, certs: []const Cert) ![]u8 {
    var out: std.Io.Writer.Allocating = .init(allocator);
    defer out.deinit();

    try out.writer.writeAll(
        \\// Generated by tools/gen_cacert.zig
        \\// Source: https://curl.se/ca/cacert.pem
        \\
    );
    try out.writer.print(
        \\// Certificate count: {d}
        \\
        \\
    , .{certs.len});

    try out.writer.writeAll(
        \\const std = @import("std");
        \\const Certificate = std.crypto.Certificate;
        \\const Allocator = std.mem.Allocator;
        \\
        \\
    );

    // Write the DER certificate array
    try out.writer.writeAll("const der_certs = [_][]const u8{\n");
    for (certs) |cert| {
        try out.writer.print("    // {s}\n    \"", .{cert.label});
        for (cert.der) |byte| {
            try out.writer.print("\\x{x:0>2}", .{byte});
        }
        try out.writer.writeAll("\",\n");
    }
    try out.writer.writeAll("};\n\n");

    // Write the addToBundle function
    try out.writer.writeAll(
        \\pub fn addToBundle(bundle: *Certificate.Bundle, gpa: Allocator, now_sec: i64) !void {
        \\    for (der_certs) |cert_der| {
        \\        const decoded_start: u32 = @intCast(bundle.bytes.items.len);
        \\        try bundle.bytes.appendSlice(gpa, cert_der);
        \\        bundle.parseCert(gpa, decoded_start, now_sec) catch |err| switch (err) {
        \\            error.CertificateHasUnrecognizedObjectId => {},
        \\            else => |e| return e,
        \\        };
        \\    }
        \\}
        \\
    );

    return try out.toOwnedSlice();
}

fn writeIfChanged(io: std.Io, allocator: std.mem.Allocator, path: []const u8, new_content: []const u8) !bool {
    const existing = std.Io.Dir.cwd().readFileAlloc(io, path, allocator, .limited(8 * 1024 * 1024)) catch |err| switch (err) {
        error.FileNotFound => null,
        else => return err,
    };
    defer if (existing) |buf| allocator.free(buf);

    if (existing) |buf| {
        if (std.mem.eql(u8, buf, new_content)) return false;
    }

    try std.Io.Dir.cwd().writeFile(io, .{
        .sub_path = path,
        .data = new_content,
        .flags = .{ .truncate = true },
    });
    return true;
}

pub fn main(init: std.process.Init) !void {
    const allocator = init.arena.allocator();

    std.debug.print("fetching {s}...\n", .{source_url});
    const pem = try fetchSource(allocator, init.io);
    std.debug.print("downloaded {d} bytes\n", .{pem.len});

    const certs = try parsePem(allocator, pem);
    std.debug.print("parsed {d} certificates\n", .{certs.len});

    const generated = try render(allocator, certs);
    const changed = try writeIfChanged(init.io, allocator, out_path, generated);

    if (changed) {
        std.debug.print("updated {s}\n", .{out_path});
    } else {
        std.debug.print("no changes in {s}\n", .{out_path});
    }
}
